### ISSUE TITLE
Unknown method: setCustom is not a valid method of interface razer.device.lighting.chroma

### ISSUE THREAD

**Issue by cyrinux** [DanManN/vim-razer#4]
Hi, 
I have this error, i run archlinux with neovim-razer-git  package.
Any idea?

```
Error detected while processing function ResetKeyboardColor[3]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "/usr/share/nvim/runtime/plugin/mode_colors.py", line 53, in <module>
    keyboard.fx.advanced.draw()
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 594, in _draw
    self._lighting_dbus.setCustom()
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: setCustom is not a valid method of interface razer.device.lighting.chroma
```

**Comment by DanManN** [comment]
My first guess is to ask if you have neovim-python3 installed but you probably already do or you wouldn't have been able to install the package from aur. Either way check that first. I'll try to test in a few days but I don't have my keyboard at the moment.

**Comment by cyrinux** [comment]
Yes, i have it installed. thanks. I have not precise . Keyboard is a razer ornata green . Say me how incan help. ☺

**Comment by DanManN** [comment]
I can't seem to reproduce the error. Do you have the latest razer drivers? Also is the openrazer-daemon running? If you are not sure, send me the output of 'pacman -Qs razer' and 'ps aux | grep razer'.

**Comment by cyrinux** [comment]
Hi @DanManN ,

Yes I use last drivers, fyi, i can for example have a green wave using polychromatic, or other mod too, like color under key i press.

```
❯ pacman -Qs razer 
local/openrazer-daemon 2.3.0-1
    Userspace daemon that abstracts access to the kernel driver. Provides a DBus service for applications to use.
local/openrazer-driver-dkms 2.3.0-1
    Kernel driver for Razer devices (DKMS-variant)
local/polychromatic 0.3.12-1
    A graphical front end for managing Razer peripherals under GNU/Linux.
local/python-openrazer 2.3.0-1
    Python library for accessing the Razer daemon from Python.
                                                                                                                                                                                                                  
❯ ps faux |grep razer  
cyril     1850  0.0  0.1 534284 32924 ?        Ssl  Jun17   0:00  \_ openrazer-daemon
cyril    28550  0.0  0.0  10924  2348 pts/3    S+   08:12   0:00      \_ grep --color razer
```

**Comment by DanManN** [comment]
Wait a min, I just realized! A razer ornata green, you said. That only does green backlight correct? I think I might have an idea of how to fix this finally.

**Comment by DanManN** [comment]
Can you run the mapLayout.py file included in this repo? I want to see if it causes the same error.

**Comment by cyrinux** [comment]
@DanManN yes only green backlight 👽

**Comment by cyrinux** [comment]
Hey @DanManN , here the return 🤣 

```
❯ python3 ./mapLayout.py
Found 1 Razer devices

6, 22
row: 0 col: 0
Traceback (most recent call last):
  File "./mapLayout.py", line 27, in <module>
    device.fx.advanced.draw()
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 594, in _draw
    self._lighting_dbus.setCustom()
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: setCustom is not a valid method of interface razer.device.lighting.chroma
```

If i remove "device.fx.*" call this end with

```
...
row: 5 col: 20
...
row: 5 col: 21
...
Razer Ornata:
{'': (5, 21)}
```

We should use a function which simply turn on led and not set special color is it ?

We could test if it is a ornata then do this?

**Comment by DanManN** [comment]
That is exactly what I want to do but I can't seem to find a function that just turns an led on or off. Anyways, I updated the mapLayout.py and I want you to run the new one. If it actually works I will be surprised but that would be great. If it doesn't can you delete the same lines you deleted before because I still want to see the output of the print statements.

**Comment by cyrinux** [comment]
Hi @DanManN, I will try this on monday thanks, razer is stay at work ;)

**Comment by cyrinux** [comment]
Hi!
I have comment `device.fx.advanced.draw()` for the second run below.

```
❯ python3 ./mapLayout.py
Found 1 Razer devices

6, 22
row: 0 col: 0
(0, 0, 0)
Traceback (most recent call last):
  File "./mapLayout.py", line 31, in <module>
    device.fx.advanced.draw()
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3.6/site-packages/openrazer/client/fx.py", line 594, in _draw
    self._lighting_dbus.setCustom()
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: setCustom is not a valid method of interface razer.device.lighting.chroma

                                                                                                                                                                                                                  
17:27:50 in .../src/personal/vim-razer on  master ⏺ at ☸️ minikube 
❯ vim mapLayout.py 
                                                                                                                                                                                                                  
17:28:19 in .../src/personal/vim-razer on  master ⏺⏺ at ☸️ minikube took 19s 
❯ python3 ./mapLayout.py
Found 1 Razer devices

6, 22
row: 0 col: 0
(0, 0, 0)
...
row: 0 col: 1
(0, 0, 0)
...
row: 0 col: 2
(0, 0, 0)
...
row: 0 col: 3
(0, 0, 0)
...
row: 0 col: 4
(0, 0, 0)
...
row: 0 col: 5
(0, 0, 0)
...
row: 0 col: 6
(0, 0, 0)
...
row: 0 col: 7
(0, 0, 0)
...
row: 0 col: 8
(0, 0, 0)
...
row: 0 col: 9
(0, 0, 0)
...
row: 0 col: 10
(0, 0, 0)
...
row: 0 col: 11
(0, 0, 0)
...
row: 0 col: 12
(0, 0, 0)
...
row: 0 col: 13
(0, 0, 0)
...
row: 0 col: 14
(0, 0, 0)
...
row: 0 col: 15
(0, 0, 0)
...
row: 0 col: 16
(0, 0, 0)
...
row: 0 col: 17
(0, 0, 0)
...
row: 0 col: 18
(0, 0, 0)
...
row: 0 col: 19
(0, 0, 0)
...
row: 0 col: 20
(0, 0, 0)
...
row: 0 col: 21
(0, 0, 0)
...
row: 1 col: 0
(0, 0, 0)
...
row: 1 col: 1
(0, 0, 0)
...
row: 1 col: 2
(0, 0, 0)
...
row: 1 col: 3
(0, 0, 0)
...
row: 1 col: 4
(0, 0, 0)
...
row: 1 col: 5
(0, 0, 0)
...
row: 1 col: 6
(0, 0, 0)
...
row: 1 col: 7
(0, 0, 0)
...
row: 1 col: 8
(0, 0, 0)
...
row: 1 col: 9
(0, 0, 0)
...
row: 1 col: 10
(0, 0, 0)
...
row: 1 col: 11
(0, 0, 0)
...
row: 1 col: 12
(0, 0, 0)
...
row: 1 col: 13
(0, 0, 0)
...
row: 1 col: 14
(0, 0, 0)
...
row: 1 col: 15
(0, 0, 0)
...
row: 1 col: 16
(0, 0, 0)
...
row: 1 col: 17
(0, 0, 0)
...
row: 1 col: 18
(0, 0, 0)
...
row: 1 col: 19
(0, 0, 0)
...
row: 1 col: 20
(0, 0, 0)
...
row: 1 col: 21
(0, 0, 0)
...
row: 2 col: 0
(0, 0, 0)
...
row: 2 col: 1
(0, 0, 0)
...
row: 2 col: 2
(0, 0, 0)
...
row: 2 col: 3
(0, 0, 0)
...
row: 2 col: 4
(0, 0, 0)
...
row: 2 col: 5
(0, 0, 0)
...
row: 2 col: 6
(0, 0, 0)
...
row: 2 col: 7
(0, 0, 0)
...
row: 2 col: 8
(0, 0, 0)
...
row: 2 col: 9
(0, 0, 0)
...
row: 2 col: 10
(0, 0, 0)
...
row: 2 col: 11
(0, 0, 0)
...
row: 2 col: 12
(0, 0, 0)
...
row: 2 col: 13
(0, 0, 0)
...
row: 2 col: 14
(0, 0, 0)
...
row: 2 col: 15
(0, 0, 0)
...
row: 2 col: 16
(0, 0, 0)
...
row: 2 col: 17
(0, 0, 0)
...
row: 2 col: 18
(0, 0, 0)
...
row: 2 col: 19
(0, 0, 0)
...
row: 2 col: 20
(0, 0, 0)
...
row: 2 col: 21
(0, 0, 0)
...
row: 3 col: 0
(0, 0, 0)
...
row: 3 col: 1
(0, 0, 0)
...
row: 3 col: 2
(0, 0, 0)
...
row: 3 col: 3
(0, 0, 0)
...
row: 3 col: 4
(0, 0, 0)
...
row: 3 col: 5
(0, 0, 0)
...
row: 3 col: 6
(0, 0, 0)
...
row: 3 col: 7
(0, 0, 0)
...
row: 3 col: 8
(0, 0, 0)
...
row: 3 col: 9
(0, 0, 0)
...
row: 3 col: 10
(0, 0, 0)
...
row: 3 col: 11
(0, 0, 0)
...
row: 3 col: 12
(0, 0, 0)
...
row: 3 col: 13
(0, 0, 0)
...
row: 3 col: 14
(0, 0, 0)
...
row: 3 col: 15
(0, 0, 0)
...
row: 3 col: 16
(0, 0, 0)
...
row: 3 col: 17
(0, 0, 0)
...
row: 3 col: 18
(0, 0, 0)
...
row: 3 col: 19
(0, 0, 0)
...
row: 3 col: 20
(0, 0, 0)
...
row: 3 col: 21
(0, 0, 0)
...
row: 4 col: 0
(0, 0, 0)
...
row: 4 col: 1
(0, 0, 0)
...
row: 4 col: 2
(0, 0, 0)
...
row: 4 col: 3
(0, 0, 0)
...
row: 4 col: 4
(0, 0, 0)
...
row: 4 col: 5
(0, 0, 0)
...
row: 4 col: 6
(0, 0, 0)
...
row: 4 col: 7
(0, 0, 0)
...
row: 4 col: 8
(0, 0, 0)
...
row: 4 col: 9
(0, 0, 0)
...
row: 4 col: 10
(0, 0, 0)
...
row: 4 col: 11
(0, 0, 0)
...
row: 4 col: 12
(0, 0, 0)
...
row: 4 col: 13
(0, 0, 0)
...
row: 4 col: 14
(0, 0, 0)
...
row: 4 col: 15
(0, 0, 0)
...
row: 4 col: 16
(0, 0, 0)
...
row: 4 col: 17
(0, 0, 0)
...
row: 4 col: 18
(0, 0, 0)
...
row: 4 col: 19
(0, 0, 0)
...
row: 4 col: 20
(0, 0, 0)
...
row: 4 col: 21
(0, 0, 0)
...
row: 5 col: 0
(0, 0, 0)
...
row: 5 col: 1
(0, 0, 0)
...
row: 5 col: 2
(0, 0, 0)
...
row: 5 col: 3
(0, 0, 0)
...
row: 5 col: 4
(0, 0, 0)
...
row: 5 col: 5
(0, 0, 0)
...
row: 5 col: 6
(0, 0, 0)
...
row: 5 col: 7
(0, 0, 0)
...
row: 5 col: 8
(0, 0, 0)
...
row: 5 col: 9
(0, 0, 0)
...
row: 5 col: 10
(0, 0, 0)
...
row: 5 col: 11
(0, 0, 0)
...
row: 5 col: 12
(0, 0, 0)
...
row: 5 col: 13
(0, 0, 0)
...
row: 5 col: 14
(0, 0, 0)
...
row: 5 col: 15
(0, 0, 0)
...
row: 5 col: 16
(0, 0, 0)
...
row: 5 col: 17
(0, 0, 0)
...
row: 5 col: 18
(0, 0, 0)
...
row: 5 col: 19
(0, 0, 0)
...
row: 5 col: 20
(0, 0, 0)
...
row: 5 col: 21
(0, 0, 0)
...
Razer Ornata:
{'brightness': True,
 'firmware_version': True,
 'game_mode_led': True,
 'keyboard_layout': True,
 'lighting': True,
 'lighting_backlight': False,
 'lighting_backlight_active': False,
 'lighting_breath_dual': False,
 'lighting_breath_random': False,
 'lighting_breath_single': True,
 'lighting_breath_triple': False,
 'lighting_led_matrix': True,
 'lighting_led_single': False,
 'lighting_logo': False,
 'lighting_logo_active': False,
 'lighting_logo_blinking': False,
 'lighting_logo_breath_dual': False,
 'lighting_logo_breath_random': False,
 'lighting_logo_breath_single': False,
 'lighting_logo_brightness': False,
 'lighting_logo_none': False,
 'lighting_logo_pulsate': False,
 'lighting_logo_reactive': False,
 'lighting_logo_spectrum': False,
 'lighting_logo_static': False,
 'lighting_none': True,
 'lighting_pulsate': False,
 'lighting_reactive': True,
 'lighting_ripple': True,
 'lighting_ripple_random': True,
 'lighting_scroll': False,
 'lighting_scroll_active': False,
 'lighting_scroll_blinking': False,
 'lighting_scroll_breath_dual': False,
 'lighting_scroll_breath_random': False,
 'lighting_scroll_breath_single': False,
 'lighting_scroll_brightness': False,
 'lighting_scroll_none': False,
 'lighting_scroll_pulsate': False,
 'lighting_scroll_reactive': False,
 'lighting_scroll_spectrum': False,
 'lighting_scroll_static': False,
 'lighting_spectrum': False,
 'lighting_starlight_dual': False,
 'lighting_starlight_random': False,
 'lighting_starlight_single': True,
 'lighting_static': True,
 'lighting_wave': True,
 'macro_logic': True,
 'macro_mode_led': True,
 'macro_mode_led_effect': True,
 'macro_mode_modifier': False,
 'name': True,
 'serial': True,
 'type': True}
{'': (5, 21)}
```

**Comment by DanManN** [comment]
Sorry for the delayed response, I've been busy with other matters. Could you run the updated version of the file again and show me the output?

**Comment by cyrinux** [comment]
Hi @DanManN, no problem, I will be able to try in 2 weeks ;) 
If you can envisage to study kakoune implementation also ... 👍
